# app settings

debug : true

spring:
  thymeleaf:
    cache: false

---
spring:
  profiles: cloud

---
httppool:
  maxPerRoute: 100
  maxTotal: 1000
  connectionRequestTimeout: 3000
  connectTimeout: 300
  socketTimeout: 3000
spring:
  profiles: default
  dataSource:
    driverClassName : org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/import_tool
    password : amp321
    username : amp
    
  jpa:
    database : POSTGRESQL
    hibernate:
      ddl-auto : update
      show-sql: true

