# app settings

debug: false

spring:
  thymeleaf:
    cache: false

---
spring:
  profiles: cloud

---
spring:
  profiles: default
  dataSource:
    driverClassName : org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/import_tool
    password : amp321
    username : amp

  jpa:
    database : POSTGRESQL
    hibernate:
      ddl-auto : update
    show-sql: false

#logging.level:
#  org.apache.http.wire: DEBUG
