# app settings

debug : true

spring:
  thymeleaf:
    cache: false

---
spring:
  profiles: cloud

---
spring:
  profiles: default
  dataSource:
    driverClassName : org.h2.Driver
    url: jdbc:h2:~/import_tool
    password : 
    username : sa
    
  jpa:
    database : H2
    hibernate:
      ddl-auto : update
      show-sql: true

