'use strict';

module.exports = {
  UPLOAD_FILE: 'UPLOAD_FILE',
  FILTER_DATA: 'FILTER_DATA',
  CHOOSE_PROJECTS: 'CHOOSE_PROJECTS',
  CHOOSE_FIELDS: 'CHOOSE_FIELDS',
  MAP_VALUES: 'MAP_VALUES',
  REVIEW_IMPORT: 'REVIEW_IMPORT',
  STEPS_ORDER:['UPLOAD_FILE', 'FILTER_DATA', 'CHOOSE_PROJECTS', 'CHOOSE_FIELDS', 'MAP_VALUES', 'REVIEW_IMPORT'],
  DIRECTION_NEXT: 'NEXT',
  DIRECTION_PREVIOUS: 'PREVIOUS',
  FIELD_TYPE: {MULTILANG_STRING: 'MULTILANG_STRING', STRING:'STRING', LIST: 'LIST', LOCATION: 'LOCATION', DATE: 'DATE',TRANSACTION: 'TRANSACTION',ORGANIZATION: 'ORGANIZATION'},
  FIELD_TYPE_FRIENDLY_NAME: {MULTILANG_STRING: 'Multi-language', STRING:'String', LIST: 'List', LOCATION: 'Location', DATE: 'Date',TRANSACTION: 'Transaction',ORGANIZATION: 'Organization'}
};
