'use strict';

module.exports = {
  UPLOAD_FILE: 'UPLOAD_FILE',
  FILTER_DATA: 'FILTER_DATA',
  CHOOSE_PROJECTS: 'CHOOSE_PROJECTS',
  CHOOSE_FIELDS: 'CHOOSE_FIELDS',
  MAP_VALUES: 'MAP_VALUES',
  REVIEW_IMPORT: 'REVIEW_IMPORT',
  SELECT_DATASOURCE: 'SELECT_DATASOURCE',
  SELECT_VERSION: 'SELECT_VERSION',
  AUTOMATIC_STEPS_ORDER:['SELECT_DATASOURCE','SELECT_VERSION' ,'FILTER_DATA', 'CHOOSE_PROJECTS', 'CHOOSE_FIELDS', 'MAP_VALUES', 'REVIEW_IMPORT'],
  MANUAL_STEPS_ORDER:['UPLOAD_FILE', 'FILTER_DATA', 'CHOOSE_PROJECTS', 'CHOOSE_FIELDS', 'MAP_VALUES', 'REVIEW_IMPORT'],
  DIRECTION_NEXT: 'NEXT',
  DIRECTION_PREVIOUS: 'PREVIOUS',
  FIELD_TYPE: {MULTILANG_STRING: 'MULTILANG_STRING', STRING:'STRING', LIST: 'LIST', LOCATION: 'LOCATION', DATE: 'DATE',TRANSACTION: 'TRANSACTION',ORGANIZATION: 'ORGANIZATION'},
  FIELD_TYPE_FRIENDLY_NAME: {MULTILANG_STRING: 'Multi-language', STRING:'String', LIST: 'List', LOCATION: 'Location', DATE: 'Date',TRANSACTION: 'Transaction',ORGANIZATION: 'Organization'},
  OVERWRITE_ALL_FUNDING:'OVERWRITE_ALL_FUNDING',
  ONLY_ADD_NEW_FUNDING: 'ONLY_ADD_NEW_FUNDING',
  REPLACE_DONOR_FUNDING: 'REPLACE_DONOR_FUNDING',
  IMPORT_TYPE_MANUAL: 'manual',
  IMPORT_TYPE_AUTOMATIC: 'automatic',  
  FIELD_NAMES: {
	  IATI_ID: 'iati-identifier',
	  TITLE: 'title',
	  DESCRIPTION: 'description',
      ACTIVITY_STATUS: 'activity-status'
  }
};
